export const Titulos = {
  Explore: 'Explorar',
  ExploreMeals: 'Explorar Comidas',
  ExploreDrinks: 'Explorar Bebidas',
  ExploreIngredients: 'Explorar Ingredientes',
  ExploreOrigin: 'Explorar Origem',
  Profile: 'Perfil',
  DoneRecipes: 'Receitas Feitas',
  FavoriteRecipes: 'Receitas Favoritas',
};

export const ButtonsHidden = {
  Explore: 'Explorar',
  ExploreMeals: 'Explorar Comidas',
  ExploreDrinks: 'Explorar Bebidas',
  ExploreIngredients: 'Explorar Ingredientes',
  Profile: 'Perfil',
  DoneRecipes: 'Receitas Feitas',
  FavoriteRecipes: 'Receitas Favoritas',
};

export const MealsIngredients = [
  'strIngredient1',
  'strIngredient2',
  'strIngredient3',
  'strIngredient4',
  'strIngredient5',
  'strIngredient6',
  'strIngredient7',
  'strIngredient8',
  'strIngredient9',
  'strIngredient10',
  'strIngredient11',
  'strIngredient12',
  'strIngredient13',
  'strIngredient14',
  'strIngredient15',
  'strIngredient16',
  'strIngredient17',
  'strIngredient18',
  'strIngredient19',
  'strIngredient20',
];

export const MealsMeasure = [
  'strMeasure1',
  'strMeasure2',
  'strMeasure3',
  'strMeasure4',
  'strMeasure5',
  'strMeasure6',
  'strMeasure7',
  'strMeasure8',
  'strMeasure9',
  'strMeasure10',
  'strMeasure11',
  'strMeasure12',
  'strMeasure13',
  'strMeasure14',
  'strMeasure15',
  'strMeasure16',
  'strMeasure17',
  'strMeasure18',
  'strMeasure19',
  'strMeasure20',
];

export const DrinksIngredients = [
  'strIngredient1',
  'strIngredient2',
  'strIngredient3',
  'strIngredient4',
  'strIngredient5',
  'strIngredient6',
  'strIngredient7',
  'strIngredient8',
  'strIngredient9',
  'strIngredient10',
  'strIngredient11',
  'strIngredient12',
  'strIngredient13',
  'strIngredient14',
  'strIngredient15',
];

export const DrinksMeasures = [
  'strMeasure1',
  'strMeasure2',
  'strMeasure3',
  'strMeasure4',
  'strMeasure5',
  'strMeasure6',
  'strMeasure7',
  'strMeasure8',
  'strMeasure9',
  'strMeasure10',
  'strMeasure11',
  'strMeasure12',
  'strMeasure13',
  'strMeasure14',
  'strMeasure15',
];
